QUESTIONS = [
    {
        'id': 'fisma_system_location',
        'type': 'text_area',
        'label': 'List your FISMA system and the primary operating location of your system? (ABCD/AWS Cloud, FEGH/EDC4 etc)'
    },
    {
        'id': 'cisa_edr_tools',
        'type': 'multiselect',
        'label': 'What CISA Approved Endpoint Detection & Response (EDR) Tool do you use? (Select all that apply)',
        "options": [
            'CrowdStrike — Falcon Control and Respond Tier *',
            'CrowdStrike — Cloud Runtime Protection - On Demand',
            'CrowdStrike — CWP Reserved License - Falcon Sensor',
            'CrowdStrike — CWP Reserved License - Falcon Sensor - Tier *',
            'CrowdStrike — CWP Reserved License - LUMOS Sensor',
            'CrowdStrike — CWP Reserved License - LUMOS Sensor - Tier *',
            'CrowdStrike — CWP On Demand - Falcon Sensor - Flex Bundle',
            'CrowdStrike — CWP On Demand - LUMOS Sensor - Flex Bundle',
            'CrowdStrike — CWP Reserved License - Falcon Sensor - Hard Bundle',
            'CrowdStrike — CWP Reserved License - Falcon Sensor - Hard Bundle - Tier *',
            'CrowdStrike — CWP Reserved License - LUMOS Sensor - Hard Bundle',
            'CrowdStrike — CWP Reserved License - LUMOS Sensor - Hard Bundle - Tier *',
            'CrowdStrike — CWP On Demand - Falcon Sensor - Hard Bundle',
            'CrowdStrike — CWP On Demand - LUMOS Sensor - Hard Bundle',
            'CrowdStrike — CWP On Demand Prepayment',
            'CrowdStrike — CWP Upgrade Tier *',
            'CrowdStrike — Discover for Cloud & Container - On Demand',
            'CrowdStrike — Falcon Discover for Cloud & Containers Tier *',
            'CrowdStrike — Falcon Device Control - Tier *',
        ]
    },
    {
        'id': 'other_oa_cdm_tools',
        'type': 'multiselect',
        'label': 'Are there other EDR tools being used in for ongoing authorization(OA) compliance and/or CDM reporting?',
        "options": [
            'Absolute Secure Endpoint (Absolute Visibility, Absolute Control, Absolute Resilience)',
            'Access and Identity Management',
            'Access Management',
            'ACF2',
            'Advanced Data Security (DL)',
            'Analyst1',
            'Analytics',
            'Appian Government Cloud (AGC)',
            'Application Control',
            'Application Controller',
            'Application Security',
            'AppScan',
            'Arbor AED',
            'ARMIS AFE',
            'Aruba Clearpass',
            'Asset',
            'Attack Surface Intelligence',
            'BigFix',
            'Binary Armor SCADA Network Guard',
            'Black Kite',
            'BlackBerry Protect with Optics',
            'BlackBerry UEM Enterprise Mobility Management',
            'CASB',
            'Case Management',
            'Central Manager',
            'Chainguard Images',
            'Change Control',
            'CimTrak',
            'Cisco Firewalls',
            'Cisco Umbrella',
            'Cleanup',
            'Cloud',
            'Cloud Access Security Broker',
            'Cloud Security',
            'Cloudflare for Government',
            'CloudLock',
            'Collibra',
            'Compliance Event Manager (CEM)',
            'Comply',
            'ConfigOS',
            'Content Security',
            'Core Platform',
            'Corelight Sensor - Network Detection and Response (Zeek Network Monitoring, Suricata IDS, Smart Packet Capture)',
            'Cortex XDR',
            'Cortex Xpanse',
            'Cribl Stream',
            'Cryptographic Agility Management (CAM)',
            'Cyber Fusion Center',
            'Cyber Security & ERM',
            'Cyber Security Asset Management',
            'Cyber Vision',
            'CyberRes',
            'Data Backup and Archive',
            'Data Classification Engine',
            'Data Protection',
            'Data Protection Management',
            'Data Security Manager (DSM) Platform',
            'DatAdvantage',
            'DBSS',
            'Deception',
            'Deep Security',
            'Delinea Enterprise PAM',
            'Deploy',
            'Development Operations and Security. (DevSecOps)',
            'Digital Dexterity Solutions',
            'Discover',
            'Eclypsium Platform',
            'EDR',
            'Elastic Stack',
            'Elastic Stack to include Elastic Cloud Enterprise, Elastic Cloud Kubernetes and Endgame',
            'Email Security',
            'Endpoint',
            'Endpoint Breach Prevention',
            'Endpoint Privilege Management',
            'Endpoint Privileged Management Window and Mac',
            'Endpoint Protection',
            'Enforce',
            'Enterprise Plus',
            'ENTERPRISE SECURITY',
            'Enterprise Security Manager (ESM)',
            'ETM (Enterprise Telephony Management) System',
            'EX',
            'Falcon Platform',
            'Firewall',
            'Firmware Vulnerability Platform',
            'Fleet Premium',
            'FortiAnalyzer',
            'FortiGate',
            'FortiManager',
            'Forward Enterprise',
            'GitLab Ultimate',
            'Guardium Data Encryption',
            'Guardium Data Protection',
            'Hardware Access Control (HAC-1)',
            'HTTP Traffic Secuirty',
            'HYCU for Enterprise Clouds',
            'IdenitityIQ (IIQ)',
            'Identity and Access Management Suite',
            'Identity Gateway (IDIG)',
            'Identity Services Engine',
            'IGA',
            'Illumio Core',
            'Immuta Data Security Platform',
            'Integrity Monitor',
            'InTERCEPT',
            'IT Service Intelligence',
            'Ivanti Neurons for MDM',
            'Lancope Security Products',
            'Layer 2 Platform',
            'Layer 7 API Gateway',
            'Logger',
            'Management',
            'Map',
            'Microsoft 365',
            'Mist',
            'Mobile Endpoint Security',
            'Mobile Security',
            'MTD',
            'NetBackup',
            'NetBrain Enterprise Edition',
            'Network Detection & Response (NDR)',
            'Network Security',
            'Network Security Management',
            'Networking',
            'NextGen SIEM Platform',
            'NFX',
            'nGenius',
            'nGeniusPULSE',
            'Nipper',
            'NodeZero',
            'NowSecure Mobile App testing',
            'NucleusGov',
            'Nutanix Platform with Additional Modules',
            'OnDMARC',
            'OnTap',
            'OT and IOT Security',
            'Packet Flow Switch (PFS)',
            'Password Safe',
            'Patch',
            'PC Matic Pro',
            'Pega Cloud For Government Platform as a Service',
            'Phantom Platform',
            'Phosphorus Enterprise xIoT Security Platform',
            'PingFederate',
            'Platform',
            'PowerProtect DD',
            'Prisma',
            'Prisma Access',
            'Privilege Management Unix/Linux',
            'Privilege Remote Access',
            'Privileged Access Management',
            'Privileged Account Security',
            'Privileged Remote Access',
            'Product',
            'Q-Audit',
            'Q-Compliance',
            'QRadar Security Info and Event Management',
            'Qsuite',
            'Qualys Gov Platform',
            'RadiantOne',
            'Red Hat Ansible Automation Platform',
            'Red Hat Enterprise Linux (RHEL)',
            'Remote Support',
            'Reveal',
            'Reveal (X)',
            'Riverbed Network Observability Suite',
            'RunCyberAssurance',
            'runZero - Enterprise Edition',
            'SD Elements',
            'Secure Client',
            'Secure Configuration Content',
            'Secure Network Analytics',
            'Security and Risk Management',
            'Security Center',
            'Security Management',
            'Security Orchestration and Response',
            'Security Orchestration Automation and Response',
            'Security Ratings',
            'ServiceNow Platform - Government Community Cloud',
            'Session Smart Networks',
            'ShadowPlex',
            'SIEM',
            'Singularity Platform',
            'Siren Platform',
            'Snowflake Data Cloud Platform',
            'Software Defined Networks',
            'SPLUNK APP FOR ENTERPRISE SECURITY',
            'SPLUNK ENTERPRISE',
            'Stealth for Federal',
            'StorageGRID',
            'Symantec Privileged Access Management',
            'Tachyon',
            'TAMZ',
            'Tenable.ad',
            'Tenable.io',
            'Tenable.ot',
            'The Platform',
            'Threat Defense',
            'Threat Intelligence',
            'Threat Response',
            'Threat Response Mitigation',
            'Tines Automation',
            'TippingPoint',
            'Top Secret',
            'Total Access Control',
            'Trust Protection Platform',
            'Umbrella',
            'Unified Endpoint Management',
            'US AI',
            'User Behavior Analytics',
            'Vault Enterprise',
            'VaultCore',
            'Verve Security Center',
            'Viakoo Action Platform',
            'Visibility',
            'VULNERABILITY INTELLIGENCE',
            'Vulnerability Management Suite',
            'Workforce & Customer Access',
            'XSIAM',
            'Zscaler Internet Access (ZIA)',
            'Zscaler Private Access (ZPA)',
            'None',
        ]
    },
    {
        'id': 'devices_test_env',
        'type': 'multiselect',
        'label': 'What types of devices are covered by EDR tools in the Test Environment? (Select all that apply)',
        "options": [
            'Workstations',
            'Servers',
            'Laptops',
            'Thin Clients',
            'Virtual Desktops',
            'Virtual Machines',
            'Tablets',
            'Smartphones',
            'Other Mobile Devices',
            'None',
        ]
    },
    {
        'id': 'devices_implementation_env',
        'type': 'multiselect',
        'label': 'What types of devices are covered by EDR tools in the Implementation Environment? (Select all that apply)',
        "options": [
            'Workstations',
            'Servers',
            'Laptops',
            'Thin Clients',
            'Virtual Desktops',
            'Virtual Machines',
            'Tablets',
            'Smartphones',
            'Other Mobile Devices',
            'None',
        ]
    },
    {
        'id': 'devices_dev_env',
        'type': 'multiselect',
        'label': 'What types of devices are covered by EDR tools in the Development Environment? (Select all that apply)',
        "options": [
            'Workstations',
            'Servers',
            'Laptops',
            'Thin Clients',
            'Virtual Desktops',
            'Virtual Machines',
            'Tablets',
            'Smartphones',
            'Other Mobile Devices',
            'None',
        ]
    },
    {
        'id': 'devices_prod_env',
        'type': 'multiselect',
        'label': 'What types of devices are covered by EDR tools in the Production Environment? (Select all that apply)',
        "options": [
            'Workstations',
            'Servers',
            'Laptops',
            'Thin Clients',
            'Virtual Desktops',
            'Virtual Machines',
            'Tablets',
            'Smartphones',
            'Other Mobile Devices',
            'None',
        ]
    },
    {
        'id': 'non_cisa_edr_tools',
        'type': 'text_area',
        'label': 'Are there any non-CISA tools being used for EDR? If yes, provide vendor name and current version.'
    },
    {
        'id': 'additional_comments',
        'type': 'text_area',
        'label': 'Additional comments or feedback?'
    },
]